Issue #82, Issue #83 - ensuring we don't keep around old pyc and pyo files / bsolenopsis now does the work of bsolenopsisant and honors the -f command line option

diff --git a/scripts/bsolenopsis b/scripts/bsolenopsis
--- a/scripts/bsolenopsis
+++ b/scripts/bsolenopsis
@@ -18,4 +18,59 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 
-bsolenopsisant -f /usr/share/solenopsis/ant/solenopsis.xml $*
+noAntJars() {
+	echo " "
+	echo "ERROR:  No Ant jars found!!!!  Cannot run solenopsis!"
+	echo " "
+	exit 1
+}
+
+if [ ! -e /usr/share/solenopsis/ant/lib/1.8.4 ]
+then
+	noAntJars
+fi
+
+ANT_CLASSPATH=`find /usr/share/solenopsis/ant/lib/1.8.4 -name \*.jar | tr -s '\n' ':'`
+
+if [ "${ANT_CLASSPATH}" = "/usr/share/solenopsis/ant/lib/1.8.4/:" ]
+then
+	noAntJars
+fi
+
+USER_FILE=/usr/share/solenopsis/ant/solenopsis.xml
+
+while [ $# -gt 0 ]
+do
+	if [ $1 = "--classpath" ]
+	then
+		shift
+
+		# Hate preceeding colons in paths...
+		if [ "${USER_CLASSPATH}" = "" ]
+		then
+			USER_CLASSPATH="$1"
+		else
+			USER_CLASSPATH="${USER_CLASSPATH}:$1"
+		fi
+	elif [ $1 = "-f" ]
+	then
+		shift
+
+		USER_FILE=$1
+	else
+		SOLENOPSIS_ARGS="${SOLENOPSIS_ARGS} $1"
+	fi
+
+	shift
+done
+
+# Hate preceeding colons in paths...
+if [ "${USER_CLASSPATH}" = "" ]
+then
+	CLASSPATH="${ANT_CLASSPATH}"
+else
+	CLASSPATH="${USER_CLASSPATH}:${ANT_CLASSPATH}"
+fi
+
+# Kick off ant...
+java -classpath ${CLASSPATH} -Dant.home=/usr/share/solenopsis/ant org.apache.tools.ant.Main -f ${USER_FILE} ${SOLENOPSIS_ARGS}
